# Generated by Django 5.2.2 on 2025-06-07 04:07

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Pokemon',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nickname', models.CharField(max_length=255)),
                ('gender', models.BooleanField()),
                ('image_url', models.URLField()),
                ('captured_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
