# Generated by Django 5.2.2 on 2025-06-08 13:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pokemon', '0003_pokemon_name_pokemon_shiny'),
    ]

    operations = [
        migrations.RenameField(
            model_name='pokemon',
            old_name='name',
            new_name='species_name',
        ),
    ]
